##
## Test Suites
##

    modified.files.includes[relevant][portal-remote-cors-test-rule]=**

    relevant.rule.names=\
        portal-remote-cors-test-rule

    test.batch.names[relevant][portal-remote-cors-test-rule]=\
        modules-integration-mysql57

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][portal-remote-cors-test-rule]=\
        apps/portal-remote/portal-remote-cors-test/*Test.java

##
## Testray
##

    testray.main.component.name=Security